### ISSUE TITLE
Blazor Question

### ISSUE THREAD

**Issue by TorreyGarland** [fiseni/SmartAnnotations#2]
Are there any issues with working with Blazor Server Apps or WASM?

**Comment by TorreyGarland** [comment]
or FluentValidation?

**Comment by fiseni** [comment]
The library uses source generators to generate new files on build. If the build is successful and you can see the generated files, then it doesn't make any difference if it's Blazor Server App, WASM, or anything else. It would be the same as you would have created those metadata files manually. On the other hand, it's up to the given frameworks whether they have support for data annotations or not.

Anyhow, this was just an experimental project. Please don't use it in production. Refer to this issue #1 for more details.
